module.exports = {
  // 以启动路径为根路径
  root: process.cwd(),
  hostname: '127.0.0.1',
  port:3000,
  imgName: [
    'accdb.ico',
    'avi.ico',
    'bmp.ico',
    'css.ico',
    'docx.ico',
    'eml.ico',
    'eps.ico',
    'fla.ico',
    'folder.ico',
    'gif.ico',
    'html.ico',
    'ind.ico',
    'ini.ico',
    'jpeg.ico',
    'jsf.ico',
    'midi.ico',
    'mov.ico',
    'mp3.ico',
    'mpeg.ico',
    'pdf.ico',
    'png.ico',
    'pptx.ico',
    'proj.ico',
    'psd.ico',
    'pst.ico',
    'pub.ico',
    'rar.ico',
    'readme.ico',
    'settings.ico',
    'text.ico',
    'tiff.ico',
    'unknow.ico',
    'url.ico',
    'vsd.ico',
    'wav.ico',
    'wma.ico',
    'wmv.ico',
    'xlsx.ico',
    'zip.ico'
  ],
  imgList: [
    'css.jpg',
    'folder.jpg',
    'git.jpg',
    'html.jpg',
    'js.jpg',
    'md.jpg',
    'unknow.jpg'
  ]
};
